/**
 * Auto PR Generator — GitHub and Azure DevOps
 *
 * After the healing agent patches test files and pushes a topic branch,
 * this module calls the platform API to open a draft pull request.
 *
 * Supported platforms:
 *   - GitHub (REST API v3)
 *   - Azure DevOps (REST API 7.1)
 */
import type { AIAnalysisResult, AutofixConfig, HealingPayload } from "../types/index.js";
import { createAutofixBranch } from "./branchManager.js";

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface PRResult {
  platform: "github" | "azure";
  prUrl: string;
  branchName: string;
  commitSha: string;
  patchedFiles: string[];
  skippedFiles: string[];
}

export interface PRGeneratorOptions {
  payloads: HealingPayload[];
  analyses: AIAnalysisResult[];
  autofixConfig: AutofixConfig;
  cwd: string;
}

// ─── PR body builders ──────────────────────────────────────────────────────────

function buildPRBody(
  payloads: HealingPayload[],
  analyses: AIAnalysisResult[],
  patchedFiles: string[],
  skippedFiles: string[],
  commitSha: string
): string {
  const analysisByTest = new Map(analyses.map(a => [a.testName, a]));

  const patchRows = patchedFiles
    .map(f => {
      const p = payloads.find(pl => pl.file === f);
      if (!p) return `- \`${f}\``;
      const a = analysisByTest.get(p.testName);
      const conf = Math.round(p.confidence * 100);
      const category = a?.issueCategory ?? p.actionType;
      return [
        `- **\`${f}\`** — ${p.testName}`,
        `  - 🎯 Confidence: **${conf}%** | Category: \`${category}\``,
        p.failedLocator ? `  - ❌ Failed locator: \`${p.failedLocator}\`` : null,
        p.candidateLocators.length
          ? `  - ✅ Candidate locators: ${p.candidateLocators.map(l => `\`${l}\``).join(", ")}`
          : null,
        a?.suggestedRemediation
          ? `  - 💡 ${a.suggestedRemediation}`
          : p.reasoning
          ? `  - 💡 ${p.reasoning}`
          : null,
        p.suggestedPatch
          ? `\n  <details><summary>View patch</summary>\n\n  \`\`\`diff\n  ${p.suggestedPatch.replace(/\n/g, "\n  ")}\n  \`\`\`\n\n  </details>`
          : null,
      ]
        .filter(Boolean)
        .join("\n");
    })
    .join("\n\n");

  const skippedSection =
    skippedFiles.length > 0
      ? `\n### ⚠️ Skipped (below confidence threshold)\n\n${skippedFiles.map(f => `- \`${f}\``).join("\n")}\n\nThese files were listed in the AI analysis but not patched automatically. Review manually.`
      : "";

  const analysisSection = analyses
    .map(a => {
      const conf = Math.round(a.confidence * 100);
      return [
        `#### ${a.testName}`,
        `- **Root cause**: ${a.likelyRootCause}`,
        `- **Category**: \`${a.issueCategory}\` | Confidence: **${conf}%**`,
        `- **Remediation**: ${a.suggestedRemediation}`,
      ].join("\n");
    })
    .join("\n\n");

  return [
    `## 🩹 Playwright Auto-Fix — AI-Suggested Locator Patches`,
    ``,
    `> **Draft PR** — Mandatory review required before merge.`,
    `> Commit: \`${commitSha}\``,
    ``,
    `### 📁 Patched files (${patchedFiles.length})`,
    ``,
    patchRows || "_No files patched._",
    skippedSection,
    ``,
    `---`,
    ``,
    `### 🤖 AI Analysis`,
    ``,
    analysisSection || "_No AI analyses available._",
    ``,
    `---`,
    ``,
    `### ✅ Test plan`,
    ``,
    `- [ ] Review each patched locator manually`,
    `- [ ] Run the full test suite: \`npx playwright test\``,
    `- [ ] Verify no regressions on the affected tests`,
    `- [ ] Approve and merge once green`,
    ``,
    `---`,
    ``,
    `🤖 Generated by [Playwright Glossy Reporter](https://github.com/pnakhat/playwright-spec-doc-reporter) — auto-fix`,
  ].join("\n");
}

// ─── GitHub ────────────────────────────────────────────────────────────────────

async function createGitHubPR(opts: {
  token: string;
  repo: string;   // "owner/repo"
  head: string;   // topic branch
  base: string;   // target branch
  title: string;
  body: string;
  draft: boolean;
  labels: string[];
}): Promise<string> {
  const [owner, repoName] = opts.repo.split("/");
  if (!owner || !repoName) throw new Error(`Invalid githubRepo format — expected "owner/repo", got "${opts.repo}"`);

  // Create the PR
  const createRes = await fetch(`https://api.github.com/repos/${opts.repo}/pulls`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${opts.token}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: opts.title,
      body: opts.body,
      head: opts.head,
      base: opts.base,
      draft: opts.draft,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.text().catch(() => "");
    throw new Error(`GitHub PR creation failed (${createRes.status}): ${err}`);
  }

  const pr = await createRes.json() as { number: number; html_url: string };
  const prNumber = pr.number;
  const prUrl = pr.html_url;

  // Apply labels (best-effort — label may not exist)
  if (opts.labels.length > 0) {
    // Ensure labels exist
    for (const label of opts.labels) {
      await fetch(`https://api.github.com/repos/${opts.repo}/labels`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${opts.token}`,
          "Accept": "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ name: label, color: "0075ca" }),
      }).catch(() => { /* label may already exist */ });
    }

    await fetch(`https://api.github.com/repos/${opts.repo}/issues/${prNumber}/labels`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${opts.token}`,
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ labels: opts.labels }),
    }).catch(() => { /* labels are best-effort */ });
  }

  return prUrl;
}

// ─── Azure DevOps ──────────────────────────────────────────────────────────────

async function createAzurePR(opts: {
  token: string;
  org: string;     // https://dev.azure.com/myorg
  project: string;
  repo: string;
  head: string;
  base: string;
  title: string;
  body: string;
  draft: boolean;
}): Promise<string> {
  const org = opts.org.replace(/\/$/, "");
  const apiBase = `${org}/${opts.project}/_apis/git/repositories/${opts.repo}`;
  const auth = Buffer.from(`:${opts.token}`).toString("base64");

  const res = await fetch(`${apiBase}/pullrequests?api-version=7.1`, {
    method: "POST",
    headers: {
      "Authorization": `Basic ${auth}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: opts.title,
      description: opts.body,
      sourceRefName: `refs/heads/${opts.head}`,
      targetRefName: `refs/heads/${opts.base}`,
      isDraft: opts.draft,
    }),
  });

  if (!res.ok) {
    const err = await res.text().catch(() => "");
    throw new Error(`Azure DevOps PR creation failed (${res.status}): ${err}`);
  }

  const pr = await res.json() as { pullRequestId: number };
  return `${org}/${opts.project}/_git/${opts.repo}/pullrequest/${pr.pullRequestId}`;
}

// ─── Main entry point ──────────────────────────────────────────────────────────

/**
 * Apply AI patches, push a topic branch, and create a draft PR.
 *
 * Called by the reporter after `onEnd` when `healing.generatePR: true`.
 */
export async function generateAutofixPR(opts: PRGeneratorOptions): Promise<PRResult | null> {
  const { payloads, analyses, autofixConfig: cfg, cwd } = opts;

  const platform = cfg.platform ?? "github";
  const baseBranch = cfg.baseBranch ?? "main";
  const minConfidence = cfg.minConfidence ?? 0.7;
  const createBackup = cfg.createBackup ?? true;
  const draft = cfg.draft ?? true;
  const labels = cfg.labels ?? ["auto-fix", "test-failure", "ai-generated"];

  const actionablePayloads = payloads.filter(p => p.suggestedPatch);
  if (actionablePayloads.length === 0) {
    console.log("[glossy-reporter] Auto-PR skipped — no payloads with suggestedPatch.");
    return null;
  }

  // ── 1. Create branch + apply patches + push ────────────────────────────────
  let branchResult: Awaited<ReturnType<typeof createAutofixBranch>>;
  try {
    branchResult = await createAutofixBranch({
      payloads: actionablePayloads,
      cwd,
      minConfidence,
      createBackup,
    });
  } catch (err) {
    console.error("[glossy-reporter] Auto-PR branch creation failed:", err instanceof Error ? err.message : err);
    return null;
  }

  const { branchName, commitSha, patchedFiles, skippedFiles } = branchResult;

  // ── 2. Build PR content ────────────────────────────────────────────────────
  const firstTest = actionablePayloads[0]?.testName ?? "playwright-tests";
  const title = `fix(autofix): heal ${patchedFiles.length} failing test(s) — ${firstTest.slice(0, 60)}`;
  const body = buildPRBody(payloads, analyses, patchedFiles, skippedFiles, commitSha);

  // ── 3. Create PR on the target platform ───────────────────────────────────
  let prUrl: string;

  try {
    if (platform === "github") {
      const token = cfg.githubToken ?? process.env.GITHUB_TOKEN ?? "";
      const repo = cfg.githubRepo ?? process.env.GITHUB_REPOSITORY ?? "";
      if (!token) throw new Error("githubToken / GITHUB_TOKEN is not set.");
      if (!repo) throw new Error("githubRepo / GITHUB_REPOSITORY is not set.");

      prUrl = await createGitHubPR({ token, repo, head: branchName, base: baseBranch, title, body, draft, labels });
    } else {
      const token = cfg.azureToken ?? process.env.AZDO_TOKEN ?? "";
      const org = cfg.azureOrg ?? process.env.AZDO_ORG ?? "";
      const project = cfg.azureProject ?? process.env.AZDO_PROJECT ?? "";
      const repoName = cfg.azureRepo ?? process.env.AZDO_REPO ?? "";
      if (!token) throw new Error("azureToken / AZDO_TOKEN is not set.");
      if (!org || !project || !repoName) throw new Error("azureOrg / azureProject / azureRepo must be set for Azure DevOps.");

      prUrl = await createAzurePR({
        token,
        org,
        project,
        repo: repoName,
        head: branchName,
        base: baseBranch,
        title,
        body,
        draft,
      });
    }
  } catch (err) {
    console.error("[glossy-reporter] Auto-PR API call failed:", err instanceof Error ? err.message : err);
    return null;
  }

  console.log(`[glossy-reporter] ✅ Auto-fix PR created → ${prUrl}`);
  console.log(`[glossy-reporter]    Branch: ${branchName} | Commit: ${commitSha}`);
  console.log(`[glossy-reporter]    Patched ${patchedFiles.length} file(s), skipped ${skippedFiles.length}`);

  return { platform, prUrl, branchName, commitSha, patchedFiles, skippedFiles };
}
