/**
 * Cucumber JSON → NormalizedTestResult adapter.
 *
 * Converts Cucumber JSON reports (generated by @cucumber/cucumber JSON formatter)
 * into the NormalizedTestResult format used by playwright-spec-doc-reporter.
 *
 * Supports:
 *  - @cucumber/cucumber JSON output (--format json)
 *  - playwright-bdd generated test metadata
 *  - Any Cucumber runner that emits the standard Cucumber JSON format
 */

import fs from "node:fs";
import path from "node:path";
import type { NormalizedTestResult, TestStepInfo, TestStatus, ApiEntry } from "../types/index.js";
import { shortId } from "../utils/report.js";
import type {
  CucumberFeature,
  CucumberElement,
  CucumberStep,
  CucumberEmbedding,
  NormalizedCucumberScenario,
  NormalizedCucumberStep,
} from "./types.js";
import {
  CUCUMBER_API_REQUEST_MIME,
  CUCUMBER_API_RESPONSE_MIME,
} from "./cucumberAnnotations.js";
import { gherkinStepCategory } from "./cucumberDetector.js";

/**
 * Map Cucumber step result status to reporter TestStatus.
 */
function mapCucumberStatus(
  status: string
): TestStatus {
  switch (status) {
    case "passed": return "passed";
    case "failed": return "failed";
    case "skipped":
    case "pending":
    case "undefined":
    case "ambiguous": return "skipped";
    default: return "skipped";
  }
}

/**
 * Compute overall scenario status from its steps.
 */
function scenarioStatus(steps: NormalizedCucumberStep[]): "passed" | "failed" | "skipped" | "pending" {
  if (steps.some(s => s.status === "failed")) return "failed";
  if (steps.some(s => s.status === "pending")) return "pending";
  if (steps.every(s => s.status === "skipped")) return "skipped";
  return "passed";
}

/**
 * Normalize a keyword like "Given " → "Given"
 */
function normalizeKeyword(kw: string): string {
  return kw.trim();
}

/**
 * Convert nanoseconds to milliseconds (Cucumber duration is in nanoseconds).
 */
function nanosToMs(ns: number | undefined): number {
  if (!ns) return 0;
  return Math.round(ns / 1_000_000);
}

/**
 * Parse a Cucumber feature element (scenario) into a NormalizedCucumberScenario.
 */
function parseElement(
  feature: CucumberFeature,
  element: CucumberElement
): NormalizedCucumberScenario {
  const featureTags = (feature.tags ?? []).map(t => t.name);
  const scenarioTags = (element.tags ?? []).map(t => t.name);

  const steps: NormalizedCucumberStep[] = (element.steps ?? []).map((step: CucumberStep) => ({
    keyword: normalizeKeyword(step.keyword),
    text: step.name,
    durationMs: nanosToMs(step.result.duration),
    status: mapCucumberStatus(step.result.status) === "passed" ? "passed"
      : mapCucumberStatus(step.result.status) === "failed" ? "failed"
      : "skipped",
    errorMessage: step.result.error_message,
    embeddings: step.embeddings,
  }));

  const status = scenarioStatus(steps);
  const totalDurationMs = steps.reduce((sum, s) => sum + s.durationMs, 0);
  const failedStep = steps.find(s => s.status === "failed");

  return {
    featureName: feature.name,
    featureFile: feature.uri,
    featureTags,
    scenarioName: element.name,
    scenarioTags: [...featureTags, ...scenarioTags],
    steps,
    status,
    durationMs: totalDurationMs,
    errorMessage: failedStep?.errorMessage,
    errorStep: failedStep ? `${failedStep.keyword} ${failedStep.text}` : undefined,
  };
}

/**
 * Extract ApiEntry objects from Cucumber step embeddings.
 * Looks for embeddings with the glossy API MIME types attached via
 * attachApiRequest / attachApiResponse helpers.
 */
function extractApiEntriesFromSteps(steps: NormalizedCucumberStep[]): ApiEntry[] | undefined {
  const entries: ApiEntry[] = [];
  for (const step of steps) {
    if (!step.embeddings) continue;
    for (const emb of step.embeddings) {
      if (
        emb.mime_type === CUCUMBER_API_REQUEST_MIME ||
        emb.mime_type === CUCUMBER_API_RESPONSE_MIME
      ) {
        try {
          const raw = Buffer.from(emb.data, "base64").toString("utf-8");
          const entry = JSON.parse(raw) as ApiEntry;
          entries.push(entry);
        } catch {
          // malformed embedding — skip
        }
      }
    }
  }
  return entries.length > 0 ? entries : undefined;
}

/**
 * Extract screenshot paths from Cucumber step embeddings (image/png or image/jpeg).
 * Uses path.basename to prevent path traversal and verifies the resolved path
 * stays within outputDir before writing.
 */
function extractScreenshotsFromSteps(steps: NormalizedCucumberStep[], outputDir?: string): string[] {
  const screenshots: string[] = [];
  if (!outputDir) return screenshots;
  const resolvedOutputDir = path.resolve(outputDir);
  for (const step of steps) {
    if (!step.embeddings) continue;
    for (const emb of step.embeddings) {
      if (emb.mime_type?.startsWith("image/") && emb.name) {
        // Use basename only to prevent path traversal attacks
        const safeName = path.basename(emb.name);
        const imgPath = path.join(resolvedOutputDir, safeName);
        // Verify the resolved path stays within the output directory
        if (!path.resolve(imgPath).startsWith(resolvedOutputDir + path.sep)) continue;
        try {
          fs.writeFileSync(imgPath, Buffer.from(emb.data, "base64"));
          screenshots.push(safeName);
        } catch {
          // skip if can't write
        }
      }
    }
  }
  return screenshots;
}

/**
 * Convert a NormalizedCucumberScenario to NormalizedTestResult.
 */
function scenarioToTestResult(
  scenario: NormalizedCucumberScenario,
  outputDir?: string
): NormalizedTestResult {
  // Deduplicate tags, normalise @-prefix, always include @cucumber
  const rawTags = [...new Set(scenario.scenarioTags)].map(t =>
    t.startsWith("@") ? t : `@${t}`
  );
  const allTags = [...new Set([...rawTags, "@cucumber"])];

  const steps: TestStepInfo[] = scenario.steps.map(step => ({
    title: `${step.keyword} ${step.text}`,
    category: gherkinStepCategory(step.keyword),
    durationMs: step.durationMs,
    status: step.status === "failed" ? "failed" : "passed",
    error: step.errorMessage,
    screenshots: [],
    startedAt: scenario.startedAt,
  }));

  // Extract API entries from step embeddings (from attachApiRequest/Response helpers)
  const apiEntries = extractApiEntriesFromSteps(scenario.steps);

  // Extract screenshot paths from step embeddings
  const screenshots = extractScreenshotsFromSteps(scenario.steps, outputDir);

  // Build a stable ID from feature + scenario + file
  const idSource = `cucumber:${scenario.featureFile}:${scenario.featureName}:${scenario.scenarioName}`;
  const id = shortId(idSource);

  const statusMap: Record<string, TestStatus> = {
    passed: "passed",
    failed: "failed",
    skipped: "skipped",
    pending: "skipped",
  };

  return {
    id,
    suite: scenario.featureName,
    file: scenario.featureFile,
    title: scenario.scenarioName,
    fullName: `${scenario.featureName} > ${scenario.scenarioName}`,
    status: statusMap[scenario.status] ?? "skipped",
    expectedStatus: "passed",
    flaky: false,
    retries: 0,
    retryIndex: 0,
    durationMs: scenario.durationMs,
    source: "automated",
    tags: allTags,
    featureMeta: { name: scenario.featureName },
    scenarioDescription: scenario.scenarioName,
    behaviours: scenario.steps.map(s => `${s.keyword} ${s.text}`),
    apiEntries,
    attachments: [],
    artifacts: {
      screenshots,
      videos: [],
      traces: [],
    },
    consoleLogs: [],
    steps,
    errorMessage: scenario.errorMessage,
    startedAt: scenario.startedAt,
    finishedAt: scenario.finishedAt,
  };
}

/**
 * Parse a Cucumber JSON report file and convert to NormalizedTestResult[].
 *
 * @param jsonPath  - Absolute or relative path to the Cucumber JSON report file
 * @param outputDir - Optional path to the report output directory (used to write
 *                    extracted screenshots from Cucumber embeddings)
 * @returns Array of NormalizedTestResult objects
 */
export function parseCucumberJsonReport(jsonPath: string, outputDir?: string): NormalizedTestResult[] {
  const resolved = path.isAbsolute(jsonPath)
    ? jsonPath
    : path.resolve(process.cwd(), jsonPath);

  if (!fs.existsSync(resolved)) {
    throw new Error(`[glossy-reporter] Cucumber JSON report not found: ${resolved}`);
  }

  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(resolved, "utf-8"));
  } catch (err) {
    throw new Error(`[glossy-reporter] Failed to parse Cucumber JSON at ${resolved}: ${err}`);
  }

  if (!Array.isArray(raw)) {
    throw new Error(
      `[glossy-reporter] Cucumber JSON report must be an array of features. Got: ${typeof raw}`
    );
  }

  const features = raw as CucumberFeature[];
  const results: NormalizedTestResult[] = [];

  for (const feature of features) {
    if (!feature.elements || !Array.isArray(feature.elements)) continue;
    for (const element of feature.elements) {
      // Skip Background elements — they are setup, not scenarios
      if (element.type === "background" || element.keyword?.toLowerCase() === "background") {
        continue;
      }
      const scenario = parseElement(feature, element);
      results.push(scenarioToTestResult(scenario, outputDir));
    }
  }

  return results;
}

/**
 * Parse multiple Cucumber JSON report files.
 *
 * @param jsonPaths - Array of paths to Cucumber JSON reports
 * @returns Merged array of NormalizedTestResult objects (deduplicated by ID)
 */
export function parseCucumberJsonReports(jsonPaths: string[], outputDir?: string): NormalizedTestResult[] {
  const seen = new Map<string, NormalizedTestResult>();
  for (const p of jsonPaths) {
    try {
      const results = parseCucumberJsonReport(p, outputDir);
      for (const r of results) {
        seen.set(r.id, r);
      }
    } catch (err) {
      console.warn(`[glossy-reporter] Skipping Cucumber JSON report: ${err}`);
    }
  }
  return [...seen.values()];
}
